# Generated by Django 4.0.1 on 2022-02-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='rating'),
        ),
    ]
