# Generated by Django 4.0.1 on 2022-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(choices=[('FreeLancer', 'FreeLancer'), ('User', 'User')], max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
