# Generated by Django 4.0.1 on 2022-02-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_field_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requests_accepted',
            field=models.IntegerField(default=0, verbose_name='number of requests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='requests_asked',
            field=models.IntegerField(default=0, verbose_name='requests asked number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='total rating'),
            preserve_default=False,
        ),
    ]
