# Generated by Django 4.0.1 on 2022-02-15 21:44

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManger()),
            ],
        ),
    ]
