# Generated by Django 4.0.2 on 2022-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_requests_accepted_user_requests_asked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requests_accepted',
            field=models.IntegerField(default=0, verbose_name='number of requests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests_asked',
            field=models.IntegerField(default=0, verbose_name='requests asked number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='total rating'),
        ),
    ]
