# Generated by Django 4.0.1 on 2022-02-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_ajr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requester_id',
            new_name='requester',
        ),
    ]
