# Generated by Django 4.0.1 on 2022-02-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_ajr', '0002_rename_receiver_id_request_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='rating',
        ),
    ]
